import type { DocQueryText, Issue, SeedData } from './types'

const resultCardDocQuery = '结果卡片' as DocQueryText
const searchCalendarWeeks = [
  { label: 'W23', rangeLabel: '06/02-06/06 · S24', days: ['2', '3', '4', '5', '6'] },
  { label: 'W24', rangeLabel: '06/09-06/13 · S24', days: ['9', '10', '11', '12', '13'] },
  { label: 'W25', rangeLabel: '06/16-06/20 · S25', days: ['16', '17', '18', '19', '20'] },
]
const defaultCalendarWeeks = [
  { label: 'W1', rangeLabel: '当前周', days: ['1', '2', '3', '4', '5'] },
  { label: 'W2', rangeLabel: '下周', days: ['6', '7', '8', '9', '10'] },
]

function issue(input: Omit<Issue, 'linkedDocIds' | 'priority' | 'type'> & Partial<Pick<Issue, 'linkedDocIds' | 'priority' | 'type'>>): Issue {
  return {
    linkedDocIds: [],
    priority: 'medium',
    type: 'story',
    ...input,
  }
}

const prototypeIssues: Issue[] = [
  issue({
    key: 'SRCH-198',
    projectId: 'search',
    iterationId: 'search-s24',
    title: '向量召回 beta 开关接入',
    status: 'doing',
    priority: 'high',
    assigneeId: 'gao',
    storyPoints: 8,
    blockerReason: '等待检索资源配额确认',
    linkedDocIds: ['doc-result-card'],
  }),
  issue({
    key: 'SRCH-186',
    projectId: 'search',
    iterationId: 'search-s24',
    title: '搜索历史与收藏打通',
    status: 'review',
    assigneeId: 'zhou',
    storyPoints: 5,
    linkedDocIds: ['doc-result-card'],
  }),
  issue({
    key: 'SRCH-209',
    projectId: 'search',
    iterationId: 'search-s24',
    type: 'bug',
    title: '空格 query 命中率骤降',
    status: 'doing',
    priority: 'high',
    assigneeId: 'su',
    storyPoints: 3,
  }),
  issue({
    key: 'SRCH-201',
    projectId: 'search',
    iterationId: 'search-s24',
    type: 'tech',
    title: '检索日志接入留存分析',
    status: 'review',
    assigneeId: 'he',
    storyPoints: 3,
  }),
  issue({
    key: 'SRCH-190',
    projectId: 'search',
    iterationId: 'search-s24',
    type: 'bug',
    title: '高亮在中英混排下偶发错位',
    status: 'doing',
    assigneeId: 'chen',
    storyPoints: 2,
  }),
  issue({
    key: 'SRCH-170',
    projectId: 'search',
    iterationId: 'search-s24',
    type: 'tech',
    title: '检索指标看板上线',
    status: 'done',
    priority: 'high',
    assigneeId: 'he',
    storyPoints: 5,
    linkedDocIds: ['doc-release-checklist'],
  }),
  issue({
    key: 'SRCH-164',
    projectId: 'search',
    iterationId: 'search-s24',
    title: '搜索入口信息架构调整',
    status: 'done',
    assigneeId: 'chen',
    storyPoints: 5,
  }),
  issue({
    key: 'SRCH-159',
    projectId: 'search',
    iterationId: 'search-s24',
    type: 'task',
    title: '竞品搜索体验调研纪要',
    status: 'done',
    assigneeId: 'jiang',
    storyPoints: 2,
  }),
  issue({
    key: 'SRCH-240',
    projectId: 'search',
    iterationId: 'search-s24',
    type: 'tech',
    title: '搜索发布批次收口',
    status: 'done',
    assigneeId: 'lin',
    storyPoints: 35,
  }),
  ...Array.from({ length: 7 }, (_, index) =>
    issue({
      key: `SRCH-BUG-${index + 1}`,
      projectId: 'search',
      iterationId: 'search-s24',
      type: 'bug',
      title: `搜索回归缺陷 ${index + 1}`,
      status: 'todo',
      priority: 'low',
      assigneeId: (['lin', 'han', 'jiang', 'gao', 'su', 'chen', 'zhou'] as const)[index],
      storyPoints: 0,
    }),
  ),
  issue({
    key: 'DATA-42',
    projectId: 'data',
    iterationId: 'data-s12',
    title: '指标卡片字段配置',
    status: 'doing',
    assigneeId: 'he',
    storyPoints: 12,
  }),
  issue({
    key: 'DATA-50',
    projectId: 'data',
    iterationId: 'data-s12',
    type: 'bug',
    title: '指标口径异常修正',
    status: 'todo',
    assigneeId: 'su',
    storyPoints: 3,
  }),
  issue({
    key: 'DATA-31',
    projectId: 'data',
    iterationId: 'data-s12',
    title: '自助配置首批上线',
    status: 'done',
    assigneeId: 'jiang',
    storyPoints: 18,
  }),
  ...Array.from({ length: 2 }, (_, index) =>
    issue({
      key: `DATA-BUG-${index + 1}`,
      projectId: 'data',
      iterationId: 'data-s12',
      type: 'bug',
      title: `数据看板缺陷 ${index + 1}`,
      status: 'todo',
      priority: 'low',
      assigneeId: (['he', 'su'] as const)[index],
      storyPoints: 0,
    }),
  ),
  issue({
    key: 'API-17',
    projectId: 'api',
    iterationId: 'api-s07',
    title: '鉴权依赖',
    status: 'blocked',
    priority: 'high',
    assigneeId: 'gao',
    storyPoints: 8,
    blockerReason: '等待开放平台鉴权依赖确认',
  }),
  issue({
    key: 'API-21',
    projectId: 'api',
    iterationId: 'api-s07',
    type: 'bug',
    title: '鉴权回调异常',
    status: 'doing',
    assigneeId: 'he',
    storyPoints: 5,
  }),
  issue({
    key: 'API-22',
    projectId: 'api',
    iterationId: 'api-s07',
    title: '网关文档补齐',
    status: 'todo',
    assigneeId: 'lin',
    storyPoints: 4,
  }),
  issue({
    key: 'API-11',
    projectId: 'api',
    iterationId: 'api-s07',
    type: 'tech',
    title: '鉴权链路基线完成',
    status: 'done',
    assigneeId: 'gao',
    storyPoints: 14,
  }),
  ...Array.from({ length: 4 }, (_, index) =>
    issue({
      key: `API-BUG-${index + 1}`,
      projectId: 'api',
      iterationId: 'api-s07',
      type: 'bug',
      title: `开放平台缺陷 ${index + 1}`,
      status: 'todo',
      priority: 'low',
      assigneeId: (['gao', 'he', 'lin', 'he'] as const)[index],
      storyPoints: 0,
    }),
  ),
  issue({
    key: 'MOB-77',
    projectId: 'mobile',
    iterationId: 'mobile-s19',
    type: 'task',
    title: '离线草稿恢复验证',
    status: 'todo',
    priority: 'low',
    assigneeId: 'han',
    storyPoints: 2,
  }),
  issue({
    key: 'MOB-84',
    projectId: 'mobile',
    iterationId: 'mobile-s19',
    type: 'bug',
    title: '离线缓存边界缺陷',
    status: 'doing',
    assigneeId: 'chen',
    storyPoints: 1,
  }),
  issue({
    key: 'MOB-61',
    projectId: 'mobile',
    iterationId: 'mobile-s19',
    title: '离线缓存主链路完成',
    status: 'done',
    assigneeId: 'zhou',
    storyPoints: 27,
  }),
]

export const seedData: SeedData = {
  navItems: [
    '团队工作台',
    '项目总览',
    'Issues',
    '看板',
    '迭代统计',
    '文档',
    '成员负载',
    '每日站会',
    '排期甘特',
    '飞书',
  ],
  projects: [
    { id: 'search', name: '搜索平台', glyph: '搜', color: 'var(--accent)', activeIterationCode: 'S24' },
    { id: 'data', name: '数据看板', glyph: '数', color: '#3f6f6a', activeIterationCode: 'S12' },
    { id: 'api', name: '开放平台', glyph: '开', color: '#7d6a8f', activeIterationCode: 'S07' },
    { id: 'mobile', name: '移动端 App', glyph: '移', color: '#9a6a4a', activeIterationCode: 'S19' },
  ],
  members: [
    { id: 'lin', name: '林舟', role: 'Tech Lead', capacity: 10 },
    { id: 'chen', name: '陈牧', role: 'Frontend', capacity: 10 },
    { id: 'gao', name: '高远', role: 'Backend', capacity: 10 },
    { id: 'su', name: '苏晴', role: 'QA', capacity: 8 },
    { id: 'han', name: '韩序', role: 'Product', capacity: 8 },
    { id: 'he', name: '何川', role: 'Data', capacity: 8 },
    { id: 'jiang', name: '江月', role: 'Design', capacity: 8 },
    { id: 'zhou', name: '周然', role: 'Frontend', capacity: 8 },
  ],
  iterations: [
    {
      id: 'search-s24',
      projectId: 'search',
      code: 'S24',
      name: '搜索体验重构',
      dateRangeLabel: '06/02-06/13',
      calendarTitle: '6 月 · Sprint 24 → 25',
      calendarWeeks: searchCalendarWeeks,
      day: 7,
      totalDays: 10,
      goal: '提升搜索结果理解与召回体验',
      velocity: 46,
    },
    {
      id: 'data-s12',
      projectId: 'data',
      code: 'S12',
      name: '指标自助配置',
      dateRangeLabel: '06/03-06/14',
      calendarTitle: '6 月 · Sprint 12',
      calendarWeeks: defaultCalendarWeeks,
      day: 4,
      totalDays: 10,
      goal: '让业务方自助搭建指标卡片',
      velocity: 34,
    },
    {
      id: 'api-s07',
      projectId: 'api',
      code: 'S07',
      name: '鉴权重构',
      dateRangeLabel: '06/04-06/15',
      calendarTitle: '6 月 · Sprint 07',
      calendarWeeks: defaultCalendarWeeks,
      day: 9,
      totalDays: 10,
      goal: '统一开放平台鉴权链路',
      velocity: 29,
    },
    {
      id: 'mobile-s19',
      projectId: 'mobile',
      code: 'S19',
      name: '离线缓存',
      dateRangeLabel: '06/05-06/16',
      calendarTitle: '6 月 · Sprint 19',
      calendarWeeks: defaultCalendarWeeks,
      day: 8,
      totalDays: 10,
      goal: '改善弱网下核心任务连续性',
      velocity: 31,
    },
  ],
  issues: prototypeIssues,
  docs: [
    {
      id: 'doc-result-card',
      scope: 'project',
      projectId: 'search',
      title: '结果卡片重设计方案',
      directory: '项目文档/搜索平台/方案',
      body: [
        '# 方案说明',
        '',
        '摘要高亮、来源标、结果卡片信息结构。',
        '',
        '- 摘要命中词高亮',
        '- 来源标签统一放在标题下方',
        '- 保留关联 Issue 入口',
        '',
        '```mermaid',
        'graph TD',
        'A[用户输入] --> B[召回结果]',
        'B --> C[卡片摘要]',
        '```',
        '',
        '```diagram',
        '搜索请求 -> 召回服务 -> 摘要生成 -> 卡片展示',
        '```',
        '',
        '```mindmap',
        '卡片设计',
        '  摘要',
        '  来源标',
        '  关联 Issue',
        '```',
      ].join('\n'),
      linkedIssueKeys: ['SRCH-198', 'SRCH-186'],
      comments: [
        {
          id: 'comment-a',
          docId: 'doc-result-card',
          authorId: 'jiang',
          body: '高亮样式需要补图。',
          resolved: false,
          createdAtLabel: '12 分钟前',
        },
        {
          id: 'comment-b',
          docId: 'doc-result-card',
          authorId: 'gao',
          body: '补充灰度指标。',
          resolved: false,
          createdAtLabel: '8 分钟前',
        },
      ],
      updatedAtLabel: '12 分钟前',
    },
    {
      id: 'doc-release-checklist',
      scope: 'global',
      title: '灰度发布检查清单',
      directory: '全局文档/发布清单',
      body: '发布前检查、回滚步骤、通知模板。',
      linkedIssueKeys: ['SRCH-170'],
      comments: [],
      updatedAtLabel: '昨天',
    },
    {
      id: 'doc-issue-standard',
      scope: 'global',
      title: 'Issue 标题与验收标准规范',
      directory: '全局文档/规范',
      body: '创建 Issue 时引用，统一标题、验收标准和关联文档。',
      linkedIssueKeys: [],
      comments: [],
      updatedAtLabel: '2 天前',
    },
  ],
  standups: [
    {
      id: 'standup-search-today',
      projectId: 'search',
      dateLabel: '06 / 06',
      weekdayLabel: '星期五',
      timeLabel: '10:00-10:15',
      calendarLabel: '每日 10:00',
      items: [
        {
          memberId: 'gao',
          yesterday: ['推进 SRCH-198 beta 开关接入'],
          today: ['解除检索资源阻塞'],
          blockers: ['SRCH-198'],
        },
        {
          memberId: 'zhou',
          yesterday: ['完成 SRCH-186 联调'],
          today: ['处理 Review 意见'],
          blockers: [],
        },
        {
          memberId: 'su',
          yesterday: ['复现空格 query 问题'],
          today: ['补充回归用例'],
          blockers: [],
        },
      ],
    },
  ],
  milestones: [
    {
      id: 'ms-design',
      projectId: 'search',
      iterationId: 'search-s24',
      title: '方案冻结',
      startDay: 1,
      endDay: 2,
      status: 'done',
      ownerId: 'jiang',
    },
    {
      id: 'ms-beta',
      projectId: 'search',
      iterationId: 'search-s24',
      title: 'Beta 开关接入',
      startDay: 3,
      endDay: 7,
      status: 'risk',
      ownerId: 'gao',
    },
    {
      id: 'ms-release',
      projectId: 'search',
      iterationId: 'search-s24',
      title: '灰度发布',
      startDay: 8,
      endDay: 10,
      status: 'planned',
      ownerId: 'lin',
    },
  ],
  feishu: {
    groups: ['AgiliX 团队群'],
    queryCommands: [
      { type: 'team' },
      { type: 'blockers' },
      { type: 'docs', query: resultCardDocQuery },
    ],
    notificationTriggers: ['站会摘要', '阻塞提醒', '文档评论'],
  },
}
